name: Update Stock Data

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y \
             build-essential \
             libxml2-dev \
             libxslt-dev \
             zlib1g-dev \
             libffi-dev \
             libssl-dev \
             libta-lib0 \
             libta-lib0-dev

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update_data.py

      - name: Commit and push updated data
        run: |
          git config user.name "halssvx"
          git config user.email "farahhaala01@gmail.com"
          git add data/*.csv
          git commit -m "Auto-update stock data" || echo "No changes"
          git push
